- name: Play variables
  hosts: localhost
  connection: local
  vars:
    URL: playgoogle.com
  roles:
    - demo
  tasks:  
    - name: Print URL
      ansible.builtin.debug:
        msg: "{{ URL}}"

# in ansible we access variable with {{}}
#also, if the value is variable or starts with variable we need to quote it(double quotes preferred).

# key: "{{ val }}"
# key: "{{ val }} some other string "
# key: some - {{ val }}  # this does not require quotes 



- name: Task variables
  hosts: localhost
  connection: local
  tasks:  
    - name: Print URL
      ansible.builtin.debug:
        msg: "{{ URL}}"
      vars:
        URL: task.google.com

- name: Roles variables
  hosts: localhost
  connection: local
  roles:
    - demo


# from command line also we can send variable to ansible playbook by using -e option 
# if the same variable name comes in different location then precedence will come

# 1.CLI  variable
# 2. Task variable
# 3. role variable
# 4. play variable
 